// =================== USER TYPES ===================
export interface User {
  id: string
  name: string
  email: string
  avatar?: string
  plan: 'free' | 'pro' | 'enterprise'
  storageUsed: number
  storageTotal: number
  createdAt: Date
}

// =================== FILE TYPES ===================
export type FileType = 
  | 'folder'
  | 'image'
  | 'video'
  | 'audio'
  | 'document'
  | 'archive'
  | 'pdf'
  | 'other'

export interface CloudFile {
  id: string
  name: string
  type: FileType
  size: number
  mimeType: string
  url?: string
  thumbnailUrl?: string
  parentId?: string
  userId: string
  isStarred: boolean
  isShared: boolean
  shareLink?: string
  uploadedAt: Date
  updatedAt: Date
  metadata?: {
    width?: number
    height?: number
    duration?: number
    fps?: number
    bitrate?: number
    hasSubtitles?: boolean
  }
}

export interface Folder {
  id: string
  name: string
  parentId?: string
  userId: string
  color?: string
  icon?: string
  fileCount: number
  size: number
  createdAt: Date
  updatedAt: Date
}

// =================== UPLOAD TYPES ===================
export interface UploadTask {
  id: string
  file: File
  name: string
  size: number
  type: FileType
  progress: number
  status: 'pending' | 'uploading' | 'paused' | 'completed' | 'error'
  error?: string
  uploadedBytes: number
  speed?: number
  estimatedTime?: number
}

// =================== STORAGE TYPES ===================
export interface StorageStats {
  used: number
  total: number
  breakdown: {
    videos: number
    images: number
    documents: number
    audio: number
    other: number
  }
}

// =================== AI TYPES ===================
export interface SubtitleTrack {
  id: string
  fileId: string
  language: string
  languageCode: string
  isAutoGenerated: boolean
  url: string
  format: 'srt' | 'vtt' | 'ass'
}

export interface TranscriptionJob {
  id: string
  fileId: string
  status: 'queued' | 'processing' | 'completed' | 'failed'
  progress: number
  language?: string
  subtitles?: SubtitleTrack[]
  summary?: string
  createdAt: Date
  completedAt?: Date
}

// =================== SHARING TYPES ===================
export interface ShareLink {
  id: string
  fileId: string
  token: string
  url: string
  expiresAt?: Date
  allowDownload: boolean
  allowUpload: boolean
  password?: string
  viewCount: number
  createdAt: Date
}

// =================== NOTIFICATION TYPES ===================
export interface Notification {
  id: string
  type: 'success' | 'error' | 'warning' | 'info'
  title: string
  message?: string
  timestamp: Date
  read: boolean
  action?: {
    label: string
    href: string
  }
}

// =================== API RESPONSE TYPES ===================
export interface ApiResponse<T> {
  success: boolean
  data?: T
  error?: string
  message?: string
}

export interface PaginatedResponse<T> {
  items: T[]
  total: number
  page: number
  perPage: number
  hasMore: boolean
}

// =================== SEARCH TYPES ===================
export interface SearchResult {
  files: CloudFile[]
  folders: Folder[]
  total: number
  query: string
}

// =================== SETTINGS TYPES ===================
export interface UserSettings {
  theme: 'dark' | 'light' | 'system'
  language: 'ar' | 'en'
  autoPlay: boolean
  autoSubtitles: boolean
  defaultSubtitleLanguage: string
  notifications: {
    upload: boolean
    share: boolean
    storage: boolean
    ai: boolean
  }
  privacy: {
    publicProfile: boolean
    shareAnalytics: boolean
  }
}

// =================== VIEW TYPES ===================
export type ViewMode = 'grid' | 'list' | 'detail'
export type SortBy = 'name' | 'size' | 'date' | 'type'
export type SortOrder = 'asc' | 'desc'

export interface FileFilter {
  type?: FileType[]
  dateRange?: {
    from: Date
    to: Date
  }
  sizeRange?: {
    min: number
    max: number
  }
  isStarred?: boolean
  isShared?: boolean
}
