'use client'

import { useState, useRef, useEffect } from 'react'
import { motion, AnimatePresence } from 'framer-motion'
import {
  Cpu, Subtitles, FileText, Search, MessageCircle,
  Loader2, Check, ChevronDown, ChevronUp, Sparkles,
  Play, Clock, Tag, Globe, AlertCircle, Send,
  X, Download, Copy, BookOpen, ListChecks
} from 'lucide-react'
import toast from 'react-hot-toast'

interface Segment { index: number; start: number; end: number; text: string; textAr?: string }

interface AIResult {
  segments?:     Segment[]
  summary?:      string
  keyPoints?:    string[]
  topics?:       string[]
  hasTranslation?: boolean
  detectedLanguage?: string
  duration?:     number
  segmentCount?: number
}

interface AIPanelProps {
  fileId:    string
  fileName:  string
  mimeType:  string
  onSeek?:   (seconds: number) => void  // jump to timestamp in player
}

type Tab = 'subtitles' | 'summary' | 'search' | 'chat'

function formatTime(s: number) {
  const h = Math.floor(s / 3600)
  const m = Math.floor((s % 3600) / 60)
  const sec = Math.floor(s % 60)
  return h > 0
    ? `${h}:${String(m).padStart(2,'0')}:${String(sec).padStart(2,'0')}`
    : `${m}:${String(sec).padStart(2,'0')}`
}

// ─── Subtitles Tab ────────────────────────────────────────────────────────────
function SubtitlesTab({ fileId, mimeType, onSeek }: { fileId: string; mimeType: string; onSeek?: (s: number) => void }) {
  const [loading, setLoading]     = useState(false)
  const [result, setResult]       = useState<AIResult | null>(null)
  const [showAr, setShowAr]       = useState(false)
  const [expandedSeg, setExpandedSeg] = useState<number | null>(null)
  const isMedia = mimeType.startsWith('video/') || mimeType.startsWith('audio/')

  const generate = async () => {
    if (!isMedia) return
    setLoading(true)
    try {
      // Demo result — replace with real API call
      await new Promise(r => setTimeout(r, 2000))
      setResult({
        segments: [
          { index: 1, start: 0,    end: 4.5,  text: 'Hello and welcome to this tutorial.',   textAr: 'مرحباً بك في هذا الدرس التعليمي.' },
          { index: 2, start: 4.5,  end: 9.2,  text: 'Today we cover cloud storage and AI.',  textAr: 'سنتناول اليوم التخزين السحابي والذكاء الاصطناعي.' },
          { index: 3, start: 9.2,  end: 15.0, text: 'CloudVault AI stores your files safely.',textAr: 'يحفظ CloudVault AI ملفاتك بأمان تام.' },
          { index: 4, start: 15.0, end: 20.8, text: 'Auto subtitles are generated by Whisper.',textAr: 'يتم توليد الترجمات تلقائياً بواسطة Whisper.' },
          { index: 5, start: 20.8, end: 27.3, text: 'Smart search works inside video content.',textAr: 'يعمل البحث الذكي داخل محتوى الفيديو.' },
          { index: 6, start: 27.3, end: 33.1, text: 'Arabic translation is fully supported.',  textAr: 'الترجمة العربية مدعومة بالكامل.' },
          { index: 7, start: 33.1, end: 40.0, text: "Thanks for watching, subscribe!",         textAr: 'شكراً لمشاهدتك، اشترك الآن!' },
        ],
        hasTranslation:   true,
        detectedLanguage: 'en',
        duration:         40,
        segmentCount:     7,
      })
      toast.success('✅ تم توليد الترجمة بنجاح!')
    } catch { toast.error('فشل توليد الترجمة') }
    finally   { setLoading(false) }
  }

  const downloadSrt = () => {
    if (!result?.segments) return
    const lang = showAr ? 'ar' : 'en'
    const content = result.segments.map(s => {
      const text = showAr ? (s.textAr ?? s.text) : s.text
      const toSrt = (sec: number) => {
        const h = Math.floor(sec / 3600), m = Math.floor((sec % 3600) / 60), ss = Math.floor(sec % 60), ms = Math.round((sec % 1) * 1000)
        return `${String(h).padStart(2,'0')}:${String(m).padStart(2,'0')}:${String(ss).padStart(2,'0')},${String(ms).padStart(3,'0')}`
      }
      return `${s.index}\n${toSrt(s.start)} --> ${toSrt(s.end)}\n${text}\n`
    }).join('\n')
    const blob = new Blob([content], { type: 'text/plain; charset=utf-8' })
    const url  = URL.createObjectURL(blob)
    const a    = document.createElement('a'); a.href = url; a.download = `subtitles_${lang}.srt`; a.click()
    URL.revokeObjectURL(url)
    toast.success('تم تحميل ملف SRT')
  }

  if (!isMedia) {
    return (
      <div className="flex flex-col items-center justify-center py-12 gap-3">
        <AlertCircle className="w-10 h-10 text-white/20" />
        <p className="text-white/50 text-sm text-center">الترجمة التلقائية متاحة فقط<br/>للملفات الصوتية والمرئية</p>
      </div>
    )
  }

  return (
    <div className="space-y-4">
      {!result && (
        <div className="glass rounded-2xl p-5 text-center">
          <div className="w-14 h-14 rounded-full bg-gradient-to-br from-royal-500/20 to-violet-500/20 border border-royal-500/30 flex items-center justify-center mx-auto mb-4">
            <Subtitles className="w-7 h-7 text-royal-400" />
          </div>
          <p className="font-bold text-white mb-1">توليد ترجمة تلقائية</p>
          <p className="text-xs text-white/50 mb-4">Whisper AI · دقة 95%+ · عربي + إنجليزي</p>
          <motion.button
            whileHover={{ scale: 1.03 }} whileTap={{ scale: 0.97 }}
            onClick={generate} disabled={loading}
            className="btn-primary flex items-center gap-2 mx-auto px-6 py-2.5 text-sm disabled:opacity-60"
          >
            {loading
              ? <><Loader2 className="w-4 h-4 animate-spin" /><span>جاري التحليل...</span></>
              : <><Sparkles className="w-4 h-4" /><span>توليد الترجمة</span></>}
          </motion.button>
        </div>
      )}

      {result?.segments && (
        <>
          {/* Controls bar */}
          <div className="flex items-center justify-between gap-3 flex-wrap">
            <div className="flex items-center gap-2">
              <div className="flex gap-1 p-1 glass rounded-xl">
                <button onClick={() => setShowAr(false)} className={`px-3 py-1 rounded-lg text-xs font-medium transition-all ${!showAr ? 'bg-royal-500/50 text-white' : 'text-white/50 hover:text-white'}`}>
                  {result.detectedLanguage?.toUpperCase() ?? 'EN'}
                </button>
                {result.hasTranslation && (
                  <button onClick={() => setShowAr(true)} className={`px-3 py-1 rounded-lg text-xs font-medium transition-all ${showAr ? 'bg-royal-500/50 text-white' : 'text-white/50 hover:text-white'}`}>
                    AR عربي
                  </button>
                )}
              </div>
              <span className="text-xs text-white/40">{result.segmentCount} مقطع</span>
            </div>
            <div className="flex gap-2">
              <button onClick={downloadSrt}
                className="btn-ghost py-1.5 px-3 text-xs flex items-center gap-1.5">
                <Download className="w-3.5 h-3.5" />SRT
              </button>
              <button onClick={generate}
                className="btn-ghost py-1.5 px-3 text-xs flex items-center gap-1.5">
                <Sparkles className="w-3.5 h-3.5" />إعادة
              </button>
            </div>
          </div>

          {/* Segments list */}
          <div className="space-y-1.5 max-h-80 overflow-y-auto">
            {result.segments.map((seg) => {
              const text     = showAr ? (seg.textAr ?? seg.text) : seg.text
              const expanded = expandedSeg === seg.index

              return (
                <motion.div
                  key={seg.index}
                  layout
                  className="glass rounded-xl p-3 hover:bg-white/8 transition-all cursor-pointer group"
                  onClick={() => {
                    setExpandedSeg(expanded ? null : seg.index)
                    onSeek?.(seg.start)
                  }}
                >
                  <div className="flex items-start gap-2">
                    <button
                      onClick={(e) => { e.stopPropagation(); onSeek?.(seg.start) }}
                      className="flex-shrink-0 flex items-center gap-1 text-xs text-royal-400 font-mono bg-royal-500/10 px-2 py-0.5 rounded-lg hover:bg-royal-500/20 transition-colors mt-0.5"
                    >
                      <Play className="w-2.5 h-2.5 fill-current" />
                      {formatTime(seg.start)}
                    </button>
                    <p className="text-sm text-white/80 leading-relaxed flex-1">{text}</p>
                  </div>

                  {/* Show both languages on expand */}
                  <AnimatePresence>
                    {expanded && seg.textAr && (
                      <motion.div
                        initial={{ height: 0, opacity: 0 }}
                        animate={{ height: 'auto', opacity: 1 }}
                        exit={{ height: 0, opacity: 0 }}
                        className="mt-2 pt-2 border-t border-white/10"
                      >
                        <p className="text-xs text-white/50 mb-0.5">الأصلي:</p>
                        <p className="text-xs text-white/70">{seg.text}</p>
                        <p className="text-xs text-white/50 mt-1 mb-0.5">العربية:</p>
                        <p className="text-xs text-royal-300">{seg.textAr}</p>
                      </motion.div>
                    )}
                  </AnimatePresence>
                </motion.div>
              )
            })}
          </div>
        </>
      )}
    </div>
  )
}

// ─── Summary Tab ──────────────────────────────────────────────────────────────
function SummaryTab({ fileId, fileName }: { fileId: string; fileName: string }) {
  const [loading, setLoading]   = useState(false)
  const [result, setResult]     = useState<AIResult | null>(null)
  const [copied, setCopied]     = useState(false)

  const generate = async () => {
    setLoading(true)
    try {
      await new Promise(r => setTimeout(r, 1800))
      setResult({
        summary: 'هذا الفيديو التعليمي يشرح بالتفصيل منصة CloudVault AI للتخزين السحابي الذكي. يتناول المحتوى كيفية استخدام الذكاء الاصطناعي لتوليد الترجمات وتلخيص المحتوى وإجراء البحث الذكي داخل الملفات.',
        keyPoints: [
          'منصة CloudVault AI توفر 2TB تخزين مجاني',
          'Whisper AI يولّد الترجمات بدقة 95%+',
          'البحث الذكي يعمل داخل محتوى الفيديو',
          'دعم كامل للغة العربية والترجمة التلقائية',
          'واجهة متجاوبة تعمل على الجوال والحاسوب',
        ],
        topics: ['تخزين سحابي', 'ذكاء اصطناعي', 'ترجمة تلقائية', 'بحث ذكي'],
      })
      toast.success('✅ تم توليد الملخص!')
    } catch { toast.error('فشل توليد الملخص') }
    finally   { setLoading(false) }
  }

  const copySummary = () => {
    if (!result?.summary) return
    const text = `${result.summary}\n\nالنقاط الرئيسية:\n${result.keyPoints?.map((p, i) => `${i + 1}. ${p}`).join('\n') ?? ''}`
    navigator.clipboard.writeText(text)
    setCopied(true)
    toast.success('تم نسخ الملخص')
    setTimeout(() => setCopied(false), 2000)
  }

  return (
    <div className="space-y-4">
      {!result && (
        <div className="glass rounded-2xl p-5 text-center">
          <div className="w-14 h-14 rounded-full bg-gradient-to-br from-amber-500/20 to-orange-500/20 border border-amber-500/30 flex items-center justify-center mx-auto mb-4">
            <BookOpen className="w-7 h-7 text-amber-400" />
          </div>
          <p className="font-bold text-white mb-1">توليد ملخص ذكي</p>
          <p className="text-xs text-white/50 mb-4">GPT-4o · ملخص شامل + نقاط رئيسية + مواضيع</p>
          <motion.button
            whileHover={{ scale: 1.03 }} whileTap={{ scale: 0.97 }}
            onClick={generate} disabled={loading}
            className="btn-primary flex items-center gap-2 mx-auto px-6 py-2.5 text-sm disabled:opacity-60"
          >
            {loading
              ? <><Loader2 className="w-4 h-4 animate-spin" /><span>جاري التلخيص...</span></>
              : <><Sparkles className="w-4 h-4" /><span>توليد الملخص</span></>}
          </motion.button>
        </div>
      )}

      {result && (
        <div className="space-y-3">
          {/* Summary */}
          <div className="glass rounded-2xl p-4">
            <div className="flex items-center justify-between mb-2">
              <div className="flex items-center gap-2">
                <FileText className="w-4 h-4 text-amber-400" />
                <span className="text-sm font-bold text-white">الملخص</span>
              </div>
              <button onClick={copySummary}
                className="w-7 h-7 rounded-lg glass flex items-center justify-center text-white/40 hover:text-white transition-all">
                {copied ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
              </button>
            </div>
            <p className="text-sm text-white/80 leading-relaxed">{result.summary}</p>
          </div>

          {/* Key points */}
          {result.keyPoints?.length && (
            <div className="glass rounded-2xl p-4">
              <div className="flex items-center gap-2 mb-3">
                <ListChecks className="w-4 h-4 text-emerald-400" />
                <span className="text-sm font-bold text-white">النقاط الرئيسية</span>
              </div>
              <ul className="space-y-2">
                {result.keyPoints.map((p, i) => (
                  <li key={i} className="flex items-start gap-2 text-sm text-white/70">
                    <span className="w-5 h-5 rounded-lg bg-emerald-500/20 text-emerald-400 text-xs font-bold flex items-center justify-center flex-shrink-0 mt-0.5">
                      {i + 1}
                    </span>
                    {p}
                  </li>
                ))}
              </ul>
            </div>
          )}

          {/* Topics */}
          {result.topics?.length && (
            <div className="glass rounded-2xl p-4">
              <div className="flex items-center gap-2 mb-3">
                <Tag className="w-4 h-4 text-violet-400" />
                <span className="text-sm font-bold text-white">المواضيع</span>
              </div>
              <div className="flex flex-wrap gap-2">
                {result.topics.map((t, i) => (
                  <span key={i} className="text-xs bg-violet-500/20 border border-violet-500/30 text-violet-300 px-3 py-1 rounded-full">
                    {t}
                  </span>
                ))}
              </div>
            </div>
          )}

          <button onClick={() => setResult(null)}
            className="btn-ghost w-full text-sm py-2 flex items-center justify-center gap-1.5">
            <Sparkles className="w-3.5 h-3.5" />إعادة التوليد
          </button>
        </div>
      )}
    </div>
  )
}

// ─── Search Tab ───────────────────────────────────────────────────────────────
function SearchTab({ fileId, onSeek }: { fileId: string; onSeek?: (s: number) => void }) {
  const [query, setQuery]     = useState('')
  const [loading, setLoading] = useState(false)
  const [results, setResults] = useState<Array<{ start: number; end: number; text: string; textAr?: string }>>([])
  const [searched, setSearched] = useState(false)

  const doSearch = async () => {
    if (!query.trim()) return
    setLoading(true)
    try {
      await new Promise(r => setTimeout(r, 600))
      // Demo results
      const demo = [
        { start: 9.2,  end: 15.0, text: 'CloudVault AI stores your files safely.',    textAr: 'يحفظ CloudVault AI ملفاتك بأمان تام.' },
        { start: 20.8, end: 27.3, text: 'Smart search works inside video content.',   textAr: 'يعمل البحث الذكي داخل محتوى الفيديو.' },
      ].filter(r => r.text.toLowerCase().includes(query.toLowerCase()) || (r.textAr ?? '').includes(query))
      setResults(demo)
      setSearched(true)
    } finally { setLoading(false) }
  }

  return (
    <div className="space-y-4">
      <div className="flex gap-2">
        <div className="relative flex-1">
          <Search className="absolute right-3 top-1/2 -translate-y-1/2 w-4 h-4 text-white/30" />
          <input
            value={query}
            onChange={e => setQuery(e.target.value)}
            onKeyDown={e => e.key === 'Enter' && doSearch()}
            placeholder="ابحث في محتوى الملف..."
            className="input-glass pr-10 text-sm"
          />
        </div>
        <motion.button
          whileTap={{ scale: 0.95 }}
          onClick={doSearch} disabled={loading || !query.trim()}
          className="btn-primary px-4 py-2 text-sm disabled:opacity-50 flex items-center gap-1.5"
        >
          {loading ? <Loader2 className="w-4 h-4 animate-spin" /> : <Search className="w-4 h-4" />}
        </motion.button>
      </div>

      {searched && results.length === 0 && (
        <div className="text-center py-8">
          <p className="text-white/40 text-sm">لا توجد نتائج لـ &quot;{query}&quot;</p>
        </div>
      )}

      {results.length > 0 && (
        <div className="space-y-2">
          <p className="text-xs text-white/40">{results.length} نتيجة</p>
          {results.map((r, i) => (
            <motion.div
              key={i}
              initial={{ opacity: 0, y: 6 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: i * 0.05 }}
              onClick={() => onSeek?.(r.start)}
              className="glass rounded-xl p-3 cursor-pointer hover:bg-white/8 transition-all"
            >
              <div className="flex items-center gap-2 mb-1.5">
                <button className="flex items-center gap-1 text-xs text-royal-400 font-mono bg-royal-500/10 px-2 py-0.5 rounded-lg">
                  <Clock className="w-3 h-3" />{formatTime(r.start)}
                </button>
                <span className="text-xs text-white/30">→</span>
                <span className="text-xs text-white/30 font-mono">{formatTime(r.end)}</span>
              </div>
              <p className="text-sm text-white/80 leading-relaxed">{r.text}</p>
              {r.textAr && <p className="text-xs text-royal-300 mt-1">{r.textAr}</p>}
            </motion.div>
          ))}
        </div>
      )}

      {!searched && (
        <div className="text-center py-8">
          <Search className="w-10 h-10 text-white/10 mx-auto mb-2" />
          <p className="text-white/30 text-sm">اكتب كلمة للبحث في محتوى الملف</p>
          <p className="text-white/20 text-xs mt-1">يدعم البحث العربي والإنجليزي</p>
        </div>
      )}
    </div>
  )
}

// ─── Chat Tab ─────────────────────────────────────────────────────────────────
function ChatTab({ fileId, fileName }: { fileId: string; fileName: string }) {
  const [messages, setMessages] = useState<{ role: 'user' | 'ai'; text: string }[]>([
    { role: 'ai', text: `مرحباً! أنا مساعدك الذكي لهذا الملف. يمكنني الإجابة على أسئلتك حول محتوى "${fileName}". بماذا تريد أن تعرف؟` },
  ])
  const [input, setInput]     = useState('')
  const [loading, setLoading] = useState(false)
  const bottomRef = useRef<HTMLDivElement>(null)

  useEffect(() => { bottomRef.current?.scrollIntoView({ behavior: 'smooth' }) }, [messages])

  const sendMessage = async () => {
    const text = input.trim()
    if (!text || loading) return
    setInput('')
    setMessages(prev => [...prev, { role: 'user', text }])
    setLoading(true)

    await new Promise(r => setTimeout(r, 1200))

    // Demo response
    const demoReplies: Record<string, string> = {
      default: 'بناءً على محتوى الملف، يمكنني القول أن هذا الموضوع يتعلق بتقنيات التخزين السحابي الحديثة. للمزيد من التفاصيل، يرجى توليد الترجمة أولاً.',
      وقت: 'يبدأ الحديث عن هذا الموضوع تقريباً في الدقيقة الثالثة من الملف.',
      ملخص: 'الفكرة الرئيسية للملف هي شرح منصة CloudVault AI وكيفية استخدام الذكاء الاصطناعي لتحسين تجربة التخزين السحابي.',
    }

    const reply = Object.entries(demoReplies).find(([k]) => text.includes(k))?.[1] ?? demoReplies.default
    setMessages(prev => [...prev, { role: 'ai', text: reply }])
    setLoading(false)
  }

  return (
    <div className="flex flex-col h-80">
      <div className="flex-1 overflow-y-auto space-y-3 mb-3">
        {messages.map((msg, i) => (
          <motion.div
            key={i}
            initial={{ opacity: 0, y: 6 }}
            animate={{ opacity: 1, y: 0 }}
            className={`flex gap-2 ${msg.role === 'user' ? 'flex-row-reverse' : 'flex-row'}`}
          >
            <div className={`w-7 h-7 rounded-full flex items-center justify-center flex-shrink-0 text-sm ${
              msg.role === 'ai'
                ? 'bg-gradient-to-br from-royal-500 to-violet-500'
                : 'bg-white/10'
            }`}>
              {msg.role === 'ai' ? <Cpu className="w-4 h-4 text-white" /> : '👤'}
            </div>
            <div className={`max-w-[80%] rounded-2xl px-3 py-2 text-sm leading-relaxed ${
              msg.role === 'ai'
                ? 'glass text-white/80'
                : 'bg-royal-500/20 text-white border border-royal-500/20'
            }`}>
              {msg.text}
            </div>
          </motion.div>
        ))}

        {loading && (
          <div className="flex gap-2">
            <div className="w-7 h-7 rounded-full bg-gradient-to-br from-royal-500 to-violet-500 flex items-center justify-center flex-shrink-0">
              <Cpu className="w-4 h-4 text-white" />
            </div>
            <div className="glass rounded-2xl px-4 py-3 flex items-center gap-1">
              {[0,1,2].map(i => (
                <div key={i} className="w-1.5 h-1.5 rounded-full bg-royal-400 animate-bounce" style={{ animationDelay: `${i * 0.15}s` }} />
              ))}
            </div>
          </div>
        )}
        <div ref={bottomRef} />
      </div>

      <div className="flex gap-2">
        <input
          value={input}
          onChange={e => setInput(e.target.value)}
          onKeyDown={e => e.key === 'Enter' && !e.shiftKey && sendMessage()}
          placeholder="اسأل عن محتوى الملف..."
          className="input-glass text-sm flex-1 py-2"
        />
        <motion.button
          whileTap={{ scale: 0.9 }}
          onClick={sendMessage} disabled={!input.trim() || loading}
          className="btn-primary p-2.5 disabled:opacity-50"
        >
          <Send className="w-4 h-4" />
        </motion.button>
      </div>
    </div>
  )
}

// ─── Main AIPanel component ───────────────────────────────────────────────────
export default function AIPanel({ fileId, fileName, mimeType, onSeek }: AIPanelProps) {
  const [open, setOpen]         = useState(false)
  const [activeTab, setActiveTab] = useState<Tab>('subtitles')

  const isMedia = mimeType.startsWith('video/') || mimeType.startsWith('audio/')

  const tabs: { id: Tab; label: string; icon: React.ElementType; color: string }[] = [
    { id: 'subtitles', label: 'ترجمة',   icon: Subtitles,       color: 'text-royal-400' },
    { id: 'summary',   label: 'ملخص',    icon: BookOpen,        color: 'text-amber-400' },
    { id: 'search',    label: 'بحث',     icon: Search,          color: 'text-emerald-400' },
    { id: 'chat',      label: 'محادثة',  icon: MessageCircle,   color: 'text-pink-400' },
  ]

  return (
    <div className="glass-card rounded-3xl overflow-hidden">
      {/* Header */}
      <button
        onClick={() => setOpen(!open)}
        className="w-full flex items-center gap-3 p-4 hover:bg-white/5 transition-colors"
      >
        <div className="w-9 h-9 rounded-2xl bg-gradient-to-br from-royal-500 to-violet-500 flex items-center justify-center shadow-glow-sm flex-shrink-0">
          <Cpu className="w-5 h-5 text-white" />
        </div>
        <div className="flex-1 text-right">
          <p className="font-bold text-white text-sm">مساعد AI الذكي</p>
          <p className="text-xs text-white/50">ترجمة · ملخص · بحث · محادثة</p>
        </div>
        <div className="flex items-center gap-2">
          <span className="text-xs bg-gradient-to-r from-royal-500/30 to-violet-500/30 border border-royal-500/30 text-royal-300 px-2 py-0.5 rounded-full">
            GPT-4o
          </span>
          {open
            ? <ChevronUp   className="w-4 h-4 text-white/40" />
            : <ChevronDown className="w-4 h-4 text-white/40" />}
        </div>
      </button>

      {/* Expanded panel */}
      <AnimatePresence>
        {open && (
          <motion.div
            initial={{ height: 0, opacity: 0 }}
            animate={{ height: 'auto', opacity: 1 }}
            exit={{ height: 0, opacity: 0 }}
            transition={{ duration: 0.25 }}
            className="overflow-hidden"
          >
            <div className="border-t border-white/10">
              {/* Tab bar */}
              <div className="flex border-b border-white/10">
                {tabs.map(tab => (
                  <button
                    key={tab.id}
                    onClick={() => setActiveTab(tab.id)}
                    className={`flex-1 flex flex-col items-center gap-1 py-3 transition-all text-xs font-medium ${
                      activeTab === tab.id
                        ? 'border-b-2 border-royal-500 text-white'
                        : 'text-white/40 hover:text-white/70'
                    }`}
                  >
                    <tab.icon className={`w-4 h-4 ${activeTab === tab.id ? tab.color : ''}`} />
                    {tab.label}
                  </button>
                ))}
              </div>

              {/* Tab content */}
              <div className="p-4">
                <AnimatePresence mode="wait">
                  <motion.div
                    key={activeTab}
                    initial={{ opacity: 0, y: 6 }}
                    animate={{ opacity: 1, y: 0 }}
                    exit={{ opacity: 0, y: -6 }}
                    transition={{ duration: 0.15 }}
                  >
                    {activeTab === 'subtitles' && <SubtitlesTab fileId={fileId} mimeType={mimeType} onSeek={onSeek} />}
                    {activeTab === 'summary'   && <SummaryTab   fileId={fileId} fileName={fileName} />}
                    {activeTab === 'search'    && <SearchTab    fileId={fileId} onSeek={onSeek} />}
                    {activeTab === 'chat'      && <ChatTab      fileId={fileId} fileName={fileName} />}
                  </motion.div>
                </AnimatePresence>
              </div>
            </div>
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  )
}
